name: debug
on:
  workflow_dispatch:
    inputs:
      force-version:
        description: "version tag(eg. 1.2.3)"
        default: "1.0.0"
        required: true
      force-update:
        description: "Is force update"
        required: true
        default: 'no'
        type: choice
        options: 
        - 'yes'
        - 'no'
  
  # schedule:
  # - cron: '0 * */3 * *'

jobs:
  check-update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: tree
          # - environment: side
    environment:
      name: ${{matrix.environment}}
        
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - run: npm ci
      
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: upload and handle
        id: update_with_node
        uses: actions/github-script@v6
        with:
          script: |
            const { default: script } = await import('${{ github.workspace }}/scripts/update.js')
            await script({
              github,
              context,
              core,
              exec,
              type:'${{secrets.TYPE}}',
              id:'${{secrets.ID}}',
              io
            })

      # - name: git push
      #   id: auto-commit-action
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   if: steps.update_with_node.outputs.commit_message != ''
      #   with:
      #     commit_message: ${{steps.update_with_node.outputs.commit_message}}
          
      - name: Sign commit and push changes
        id: commit_with_GPG
        if: steps.update_with_node.outputs.commit_message != ''
        run: |
          git add .
          git commit -S -m "${{steps.update_with_node.outputs.commit_message}}"
          git push

      - name: "Run if changes have been detected"
        if: steps.commit_with_GPG.outputs.changes_detected == 'true'
        run: echo "updated!"

      - name: "Run if no changes have been detected"
        if: steps.commit_with_GPG.outputs.changes_detected == 'false'
        run: echo "No updates!"
