name: example-ngrok-kind-v2
on:
  workflow_dispatch:
    inputs:
      force-version:
        description: "version tag(eg. 1.2.3)"
        default: "1.0.0"
        required: true
      force-update-type:
        description: "Is force update"
        required: true
        default: 'no'
        type: choice
        options: 
        - 'yes'
        - 'no'

jobs:
  check-tree:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: tree
          - environment: side
    environment:
      name: ${{matrix.environment}}
        
    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: upload and handle
        id: update_with_node
        uses: actions/github-script@v6
        with:
          script: |
            const script = import('./scripts/update.js')
            await script({
              github,
              context,
              core,
              type:'{{secrets.TYPE}}',
              ver:'{{secrets.VER}}',
              id:'{{secrets.ID}}'
            })
