name: debug
on:
  workflow_dispatch:
    inputs:
      force-version:
        description: "version tag(eg. 1.2.3)"
        default: "1.0.0"
        required: true
      force-update-type:
        description: "Is force update"
        required: true
        default: 'no'
        type: choice
        options: 
        - 'yes'
        - 'no'

jobs:
  check-update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: tree
          # - environment: side
    environment:
      name: ${{matrix.environment}}
        
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - name: upload and handle
        id: update_with_node
        uses: actions/github-script@v6
        with:
          script: |
            const { default: script } = await import('${{ github.workspace }}/scripts/update.js')
            await script({
              github,
              context,
              core,
              exec,
              type:'${{secrets.TYPE}}',
              id:'${{secrets.ID}}'
            })

      - name: git push
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.update_with_node.outputs.commit_message != ''
        with:
          commit_message: ${{steps.update_with_node.outputs.commit_message}}
          
      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "updated!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No updates!"
